# Hugo build configuration for Netlify
# (https://gohugo.io/hosting-and-deployment/hosting-on-netlify/#configure-hugo-version-in-netlify)

[build]
command = "hugo --gc --minify"
publish = "public"

[build.environment]
GO_VERSION = "1.21.5"
HUGO_VERSION = "0.121.1"
HUGO_ENV = "production"

[context.production]
command = "hugo --gc --minify"


# https://github.com/netlify-labs/netlify-plugin-sitemap
[[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  buildDir = "public"
  # make sure you add a comma after each entry in the exclude list except on the last one
  exclude =[
    './public/',
    './public/concept/',
    './public/guide/',
  ]
  # append missing trailing slash to prettyURL
  trailingSlash = true
